// <auto-generated />
using System;
using AcademicPageDotNet.Button;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicPageDotNet.Migrations
{
    [DbContext(typeof(TheButtonDbContext))]
    partial class TheButtonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("AcademicPageDotNet.Button.TheButtonClick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastClickIP")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastClickTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clicks");
                });
#pragma warning restore 612, 618
        }
    }
}
